image: "rust:latest"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: "1"

.build_template: &build_script
  ### run build, test and doc
    - rustc --version && cargo --version      # Print version info for debugging
    - cargo build --release
    - cargo build --release --features 'piston'
    - cargo doc

# Install a C compiler, cmake and git into the container.
.linux_dependencies: &linux_deps
  ### run build, test and doc
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends build-essential libasound2-dev

# Install a C compiler, cmake and git into the container.
.test_template: &test_script
    - rustc --version && cargo --version      # Print version info for debugging
    - cargo test --verbose
    - cargo clippy -- -Dwarnings

windows:stable:
  script: *build_script
  stage: build
  cache:
    paths:
        - target/release/deps

macos:stable:
  script: *build_script
  stage: build
  cache:
    paths:
        - target/release/deps
    
linux:v1-31-0:
  script: *build_script
  stage: build
  before_script: *linux_deps
  cache:
    paths:
        - target/release/deps

test-linux:stable:
  script: *test_script
  stage: test
  before_script: *linux_deps

test-linux:beta:
  allow_failure: true
  image: rustdocker/rust:nightly
  script: *test_script
  stage: test
  before_script: *linux_deps
